### PR TITLE
Update addresses.md to include Polygon (Matic)

### PR DESCRIPTION
**Pull request by JUDOKICK**
Deployed v2.0.1 contracts on Polygon L2 as well.

### CODE REVIEW

**Comment by drortirosh** [comment]
we're only listing active networks (with relayers). these networks are not active yet.

**Comment by JUDOKICK** [comment]
We are going to deploy relayer this week. I'll add our relayer to this PR

**Comment by JUDOKICK** [comment]
We have deployed a relayer at 

https://matic-mainnet-gsnv2-2.creol.io/gsn1

Registered and running on Matic Mainnet

**Comment by drortirosh** [comment]
while this update is OK, it is now stale, as we already upgraded our contracts to v2.2, and updated the docs to include them.

**Pull request closed without merging**
